version: '3'
services:
  secure:
    build:
      context: ./app
    ports:
      - 9002:8080
    env_file:
      - environments/test/secure.env
    environment:
      GOOGLE_APPLICATION_CREDENTIALS: /app/secrets/service_account_key.json
    volumes:
      - ./secrets:/app/secrets
  insecure:
    build:
      context: ./app
    ports:
      - 9003:8080
    env_file:
      - environments/test/insecure.env
    environment:
      GOOGLE_APPLICATION_CREDENTIALS: /app/secrets/service_account_key.json
    volumes:
      - ./secrets:/app/secrets
